singleQuote: true
tabWidth: 2
trailingComma: all
overrides:
  - files: ["*.ts", "*.mts", "*.js", "*.mjs", "*.cjs"]
    options:
      tabWidth: 4
  - files: ["*.yml", "*.yaml"]
    options:
      singleQuote: false
